### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by Midwest-Jimmy** [Itz-Hyperz/opensource-cad#2]
Is this a bubble CAD and how do I use it?

**Comment by Itz-Hyperz** [comment]
Yes, it is a bubble CAD, please note that it very clearly states "NO SUPPORT WILL BE PROVIDED!" in the readme section. Meaning if you don't already know how to import it, you are not knowledgeable enough in Bubble to be hosting this CAD. Nothing personal and it's the same thing I say to everyone.
